### PR TITLE
Modified azure.md file. Added DNS, LB and Traffic manager contents.

### PR DESCRIPTION
**Pull request by haider-ali-confiz**
Kindly review the changes that we have made in "azure.md" file (in User Reference section). Basically we have added some piece of content (DNS , LB and Traffic Manager) in it.

### CODE REVIEW

**Comment by gauravlall** [comment]
@kpgriffith  Can you please review and comment as needed

**Comment by ReneSaenz** [comment]
Please remove lines 24 and 25. They should be move after the LB components (lines 37 - 55)
Please remote your NOTE of line 55. The is some sequential steps in creating the LB components. So I would like to mislead people.

**Comment by kpgriffith** [comment]
Don't remove the link to the other Azure DNS note.  Please link to it if people want more information about Azure DNS.  That note explains that extra steps are needed if they user has a domain created and wants to send traffic to Azure from it.

**Comment by haider-ali-confiz** [comment]
Thanks for your feedback. I have made following changes.
1.   Added back the link to Azure DNS note. 
2.   Removed Note from LB section. 
3.   Removed extra lines (34,35) from LB section.

From @ReneSaenz  feedback:  "Please remove lines 24 and 25. They should be move after the LB components (lines 37 - 55)" 
"Line 24"
24. +* Followed by creating **DNS Record-Set(s)** in that zone

I was not sure where to move these lines so I left them as they are.

Please review the update.

**Comment by gauravlall** [comment]
@kpgriffith @ReneSaenz  Are we good to merge this PR.

**Comment by kpgriffith** [comment]
@gauravlall yes, please merge it.

**Pull request merged**
