### PR TITLE
Add Ning Zhang's WML Eng Blog posts to press page

### PR DESCRIPTION
**Pull request by ghost**
thank you :)

### CODE REVIEW

**Comment by mosabua** [comment]
You have to update the syntax for the links .. its [text](url)

**Comment by ghost** [comment]
When I preview it, it shows it linking. What am I doing wrong?

**Comment by ghost** [comment]
such as using < a href...?

**Comment by mosabua** [comment]
Same syntax as in the other links ..

**Comment by mosabua** [comment]
Goodie.

**Comment by ghost** [comment]
:D 
my confidence is soaring!

**Pull request merged**
